In [ ]:
# This helps to create arrays from scratch, this exercise was taken from python data science handbook.

In [59]:
import numpy as np
# Create a length-10 integer array filled with zeros
a = np.zeros(10, dtype = int)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [66]:
# Create a 3x5 floating-point array filled with 1s
a = np.ones((3,5), dtype = float)
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [68]:
# Create a 3x5 array filled with 3.14
a = np.full((3,5), 3.14)
a

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [74]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [76]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [93]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
a = np.random.random((3, 3))
a

# HINT when you just use np.random(3, 3), then you get this error:
# 'module' object is not callable

array([[0.26238393, 0.53559211, 0.63268387],
       [0.96329337, 0.8704833 , 0.49376297],
       [0.02840921, 0.5386442 , 0.33251025]])

In [96]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation` 1
a = np.random.normal(0, 1, (3, 3))
a

array([[ 0.74432586,  1.16084789, -2.34683536],
       [-1.51881723, -0.77165735,  0.04158078],
       [-2.51963937, -0.18982175,  1.01058584]])

In [98]:
# Create a 3x3 array of random integers in the interval [0, 10)
a = np.random.randint(0, 10, (3, 3))
a

array([[8, 4, 4],
       [4, 2, 7],
       [0, 9, 6]])

In [99]:
# Create a 3x3 identity matrix
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [101]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
np.empty(3)

array([1., 1., 1.])