<a href="https://colab.research.google.com/github/Tanu-N-Prabhu/Python/blob/master/Data%20Analysis/Level%201/numPy_for_numerical_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy for Numerical Operations

NumPy is the foundation of numerical computing in Python. It enables fast and efficient operations on large arrays and matrices. This guide will walk you through key operations in NumPy for data analysis.

---

## 1. Installing NumPy

To install NumPy, run:




In [1]:
!pip install numpy

## 2. Creating and Manipulating Arrays
NumPy arrays are more powerful than Python lists for numerical data.

In [2]:
import numpy as np

# Creating arrays
a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])

# Array of zeros or ones
zeros = np.zeros((2, 3))
ones = np.ones((3, 2))

# Range of numbers
ar = np.arange(0, 10, 2)   # [0, 2, 4, 6, 8]
lin = np.linspace(0, 1, 5) # 5 points between 0 and 1

In [3]:
print(a)
print(b)
print(zeros)
print(ones)
print(ar)
print(lin)

[1 2 3]
[[1 2]
 [3 4]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


## 3. Indexing, Slicing, and Reshaping

### Indexing and Slicing

In [4]:
arr = np.array([[10, 20, 30], [40, 50, 60]])
print(arr[0, 1])  # 20
print(arr[:, 1])  # column 1 -> [20, 50]
print(arr[1, :])  # row 1 -> [40, 50, 60]

20
[20 50]
[40 50 60]


### Reshaping

In [5]:
flat = np.array([1, 2, 3, 4, 5, 6])
reshaped = flat.reshape((2, 3))  # 2 rows, 3 columns
print(flat)
print(reshaped)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


## 4. Element-wise Operations
NumPy allows you to perform arithmetic on arrays directly.



In [6]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

print(x + y)    # [11, 22, 33]
print(x * 2)    # [2, 4, 6]
print(y / x)    # [10, 10, 10]

[11 22 33]
[2 4 6]
[10. 10. 10.]


Works the same way for 2D arrays as long as shapes are compatible.


## 5. Broadcasting
Broadcasting lets NumPy apply operations between arrays of different shapes.

In [7]:
# Scalar broadcast
a = np.array([1, 2, 3])
print(a + 5)  # [6, 7, 8]

# Array broadcast
b = np.array([[1], [2], [3]])
c = np.array([10, 20, 30])
print(b + c)

# Output:
# [[11 21 31]
#  [12 22 32]
#  [13 23 33]]

[6 7 8]
[[11 21 31]
 [12 22 32]
 [13 23 33]]


## 6. Aggregations: Mean, Median, Std Dev
NumPy provides fast aggregation functions:


In [8]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

# Basic aggregations
print("Mean:", arr.mean())         # Mean of all elements
print("Row-wise Mean:", arr.mean(axis=1))  # [20, 50]
print("Column-wise Mean:", arr.mean(axis=0))  # [25, 35, 45]

# Median
print("Median:", np.median(arr))

# Standard deviation
print("Std Dev:", np.std(arr))

Mean: 35.0
Row-wise Mean: [20. 50.]
Column-wise Mean: [25. 35. 45.]
Median: 35.0
Std Dev: 17.07825127659933


## Bonus: Logical Filtering

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6])
even = arr[arr % 2 == 0]  # [2, 4, 6]
print(arr)
print(even)

[1 2 3 4 5 6]
[2 4 6]


## Practice: Mini Exercise

In [11]:
# Create a 3x3 matrix with values from 1 to 9
matrix = np.arange(1, 10).reshape(3, 3)

# Multiply by 10
multiplied = matrix * 10

# Get mean of each row
row_mean = multiplied.mean(axis=1)

# Print results
print("Matrix:\n", matrix)
print("Multiplied by 10:\n", multiplied)
print("Row-wise mean:\n", row_mean)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Multiplied by 10:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Row-wise mean:
 [20. 50. 80.]


## Summary

| Concept      | Function                                |
| ------------ | --------------------------------------- |
| Create array | `np.array()`, `np.zeros()`, `np.ones()` |
| Index/Slice  | `arr[1, 2]`, `arr[:, 0]`                |
| Reshape      | `arr.reshape()`                         |
| Arithmetic   | `+`, `-`, `*`, `/`                      |
| Broadcast    | Works with compatible shapes            |
| Aggregations | `mean()`, `std()`, `median()`           |


NumPy makes data manipulation fast and intuitive. Understanding it is crucial before working with pandas.

