In [27]:
# Task 3 Zeros and Ones

# You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools numpy.zeros and numpy.ones.

# Input Format

# A single line containing the space-separated integers.

# Output Format

# First, print the array using the numpy.zeros tool and then print the array with the numpy.ones tool.

# Sample Input 0

# 3 3 3

# Sample Output 0

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]

In [28]:
# to be frank there is only one part that I got the solution for, that is how to return multiple values. And the logic part is mine.
# https://www.geeksforgeeks.org/g-fact-41-multiple-return-values-in-python/

import numpy

def arrays(arr):
    arr1 = numpy.array(arr, dtype = int)
    arr2 = numpy.zeros(arr1, dtype = int)
    arr3 = numpy.ones(arr1, dtype = int)
    return arr2, arr3

arr = input().strip().split(' ')
arr2, arr3 = arrays(arr)

print(arr2)
print(arr3)

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
