In [ ]:
# Task 5 Floor, Ceil and Rint

Input Format

A single line of input containing the space separated elements of array .

Output Format

On the first line, print the  of A. 
On the second line, print the  of A. 
On the third line, print the  of A.

Sample Input

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
Sample Output

[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]

# But I had to cheat in this example, because Hackerank has lost its mind in this exercise, because its asking for weired space throughout, 
# the exercise, which is irrelevant. So I had to sneek in one of the discussion foroums, and get the spacing problem corrected.

In [1]:
import numpy
numpy.set_printoptions(sign=' ')
def arrays(arr):
    arr1 = numpy.array(arr, dtype = float)

    floor = numpy.floor(arr1)
    ceil = numpy.ceil(arr1)
    rint = numpy.rint(arr1)

    return floor, ceil, rint    
arr = input().strip().split(' ')
floor, ceil, rint = arrays(arr)
print(floor)
print(ceil)
print(rint)


1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]
