In [ ]:
# Task 4 Array Mathematics

# You are given two integer arrays,  and  of dimensions X. 
# Your task is to perform the following operations:

Add ( + )
Subtract ( - )
Multiply ( * )
Integer Division ( / )
Mod ( % )
Power ( ** )
Input Format

The first line contains two space separated integers,  and . 
The next  lines contains  space separated integers of array . 
The following  lines contains  space separated integers of array .

Output Format

Print the result of each operation in the given order under Task.

Sample Input

1 4
1 2 3 4
5 6 7 8
Sample Output

[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]] 

Use // for division in Python 3.

# Apparently I got only 10.00 out of 20.00 because there was some issue with the looping.

In [ ]:
import numpy
def arrays(arr, arr1, arr2):
    arr = numpy.array(arr, dtype = int)
    arr1 = numpy.array([arr1], dtype = int)
    arr2 = numpy.array([arr2], dtype = int)

    add = numpy.add(arr1,arr2)
    sub = numpy.subtract(arr1, arr2)
    mul = numpy.multiply(arr1, arr2)
    div = numpy.floor_divide(arr1, arr2)
    mod = numpy.mod(arr1, arr2)
    power = numpy.power(arr1, arr2)




    return add,sub,mul,div,mod,power

arr = input().strip().split(' ')

arr1 = input().strip().split(' ')
arr2 = input().strip().split(' ')
add,sub,mul,div,mod,power = arrays(arr, arr1, arr2)
print(add)
print(sub)
print(mul)
print(div)
print(mod)
print(power)
