In [7]:
# Task2 Shape and Reshape

# You are given a space separated list of nine integers. Your task is to convert this list into a X NumPy array.

# Input Format

# A single line of input containing  space separated integers.

# Output Format

# Print the X NumPy array.

# Sample Input

# 1 2 3 4 5 6 7 8 9

# Sample Output


# [[1 2 3]
# [4 5 6]
# [7 8 9]]


In [11]:
# The solution for the above problem task is give by me !!!

import numpy

def arrays(arr):
    arr1 = numpy.array(arr, dtype = int)
    arr2 = arr1.reshape(3, 3)
    return arr2

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
