In [ ]:
# Task Eye and Identity


Your task is to print an array of size X with its main diagonal elements as 's and 's everywhere else.

Input Format
N denotes rows
M demotes coloumns

Output Format

Print the desired N X M array.

Sample Input

3 3
Sample Output

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]

In [ ]:
import numpy
numpy.set_printoptions(sign=' ')

N, M = map(int, input().split())
eye = numpy.eye(N, M)
print(eye)
