<a href="https://colab.research.google.com/github/Tanu-N-Prabhu/Python/blob/master/Numpy/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Numpy tutorial

## This notebook helps to understand numpy from scratch, this exercise was taken from python data science handbook.


![alt text](https://stackabuse.com/content/images/2018/09/numpy-tutorial-simple-example-based-guide.png)

## 1) Create a length-10 integer array filled with zeros


In [12]:
import numpy as np
a = np.zeros(10, dtype = int)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])



---



## 2) Create a 3x5 floating-point array filled with 1s


In [22]:
a = np.ones((3,5), dtype = float)
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])



---



## 3) Create a 3x5 array filled with 3.14


In [14]:
a = np.full((3,5), 3.14)
a

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])



---



## 4) Create an array filled with a linear sequence. Starting at 0, ending at 20, stepping by 2 (this is similar to the built-in range() function).

In [15]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])



---



## 5) Create an array of five values evenly spaced between 0 and 1

In [16]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])



---



## 6) Create a 3x3 array of uniformly distributed random values between 0 and 1

**HINT when you just use np.random(3, 3), then you get this error: 'module' object is not callable**

In [17]:
a = np.random.random((3, 3))
a

array([[0.92882601, 0.15277742, 0.61847288],
       [0.26835166, 0.1343164 , 0.13999919],
       [0.43270145, 0.89307018, 0.52218327]])



---



## 7) Create a 3x3 array of normally distributed random values with mean 0 and standard deviation 1

In [18]:
a = np.random.normal(0, 1, (3, 3))
a

array([[ 0.54278146, -0.29350707, -0.76737292],
       [-0.00821164, -0.49738633,  0.13785728],
       [ 1.27666228, -1.43017619, -1.2518886 ]])



---



## 8) Create a 3x3 array of random integers in the interval [0, 10)


In [19]:
a = np.random.randint(0, 10, (3, 3))
a

array([[8, 7, 3],
       [7, 7, 0],
       [1, 7, 8]])



---



## 9) Create a 3x3 identity matrix


In [20]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])



---



## 10) Create an uninitialized array of three integers. The values will be whatever happens to already exist at that memory location


In [21]:
np.empty(3)

array([1., 1., 1.])



---

